# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('resumo', models.CharField(max_length=500, verbose_name='resumo')),
                ('palavras_chave', models.CharField(max_length=200, verbose_name='palavras_chave')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.ArtigoCientifico')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('sigla', models.CharField(max_length=20, verbose_name='sigla')),
                ('dataEHoraDeInicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDeInicio')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEHoraDaInscricao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDaInscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('curriculo', models.CharField(max_length=200, verbose_name='curriculo')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('curriculo', models.CharField(max_length=200, verbose_name='curriculo')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Evento')),
                ('issn', models.CharField(max_length=200, verbose_name='issn')),
            ],
            bases=('evento.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('cpf', models.CharField(max_length=20, verbose_name='cpf')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('cnpj', models.CharField(max_length=100, verbose_name='cnpj')),
                ('razaoSocial', models.CharField(max_length=200, verbose_name='razaoSocial')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='tipoInscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.TipoInscricao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='avaliacaoartigo',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.CriterioAvaliacao'),
        ),
        migrations.AddField(
            model_name='artigoautor',
            name='artigoCientifico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.ArtigoCientifico'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='avaliacaoartigo',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Avaliador'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoCientifico'),
        ),
        migrations.AddField(
            model_name='artigoautor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Autor'),
        ),
    ]
